# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocurl < Formula
  desc "A golang HTTP curl-like tool"
  homepage "https://github.com/mrsimi/gocurl"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Darwin_arm64.tar.gz"
      sha256 "6cc6c90582411a38a87b6818afa431b27acbb920430dcb9c9186ce9c0c5f0411"

      def install
        bin.install "gocurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Darwin_x86_64.tar.gz"
      sha256 "a3c7fce40c9f08ad50d0851da110a608784a2d5d00da7f4553926b2f906ff0fd"

      def install
        bin.install "gocurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Linux_arm64.tar.gz"
      sha256 "7b43e1f437579a61f7a76eef41dede4271eed33b86d2a1a986427a9a9a6bfe69"

      def install
        bin.install "gocurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Linux_x86_64.tar.gz"
      sha256 "db13ae5400e9007793b786f1715bf6da351292b849914156792ab3cf9cbdd213"

      def install
        bin.install "gocurl"
      end
    end
  end
end
